# Assignment

In [1]:
import numpy as np

#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F") <br>
array1 = np.array(range(30))

In [43]:
array1 = np.array(range(30))

In [35]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
array1 = array1.reshape(5,6)

In [37]:
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
array1 = array1.ravel(order="F")

In [46]:
array1

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [47]:
array1 = array1.reshape(5,6)

In [48]:
array1 #######################Answer###############

array([[ 0,  6, 12, 18, 24,  1],
       [ 7, 13, 19, 25,  2,  8],
       [14, 20, 26,  3,  9, 15],
       [21, 27,  4, 10, 16, 22],
       [28,  5, 11, 17, 23, 29]])

#2.呈上題的array，找出被6除餘1的數的索引

In [49]:
np.where(array1%6 == 1) #######################Answer##################

(array([0, 1, 1, 1, 1], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))

# Practice

## 1 my array

In [50]:
array2 = np.array([[2,4,5,6],
                 [4,3,5,6],
                 [8,3,5,2]])

In [51]:
array2

array([[2, 4, 5, 6],
       [4, 3, 5, 6],
       [8, 3, 5, 2]])

### 1.1 flatten() & ravel()

In [52]:
array2.flatten()

array([2, 4, 5, 6, 4, 3, 5, 6, 8, 3, 5, 2])

In [53]:
b = array2.ravel()

In [54]:
b

array([2, 4, 5, 6, 4, 3, 5, 6, 8, 3, 5, 2])

In [55]:
b[4] = 1000

In [56]:
b

array([   2,    4,    5,    6, 1000,    3,    5,    6,    8,    3,    5,
          2])

In [57]:
array2

array([[   2,    4,    5,    6],
       [1000,    3,    5,    6],
       [   8,    3,    5,    2]])

### 1.2 reshape()

In [60]:
array2 = np.arange(30)

In [61]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [62]:
array2.reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [63]:
array2 #不變

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
b = array2.reshape(5,-1)

In [67]:
b[2,3] = 1000

In [68]:
b #變了

array([[   0,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14, 1000,   16,   17],
       [  18,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29]])

In [69]:
array2 #也變了

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14, 1000,   16,   17,   18,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29])

### 1.3 resize()

In [70]:
array2 = np.arange(30)

In [71]:
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [73]:
array2.size

30

In [79]:
array2.resize((3,6), refcheck=False) #np.resize(array2,(3,6))

In [81]:
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

## 2 axis & dimension

In [82]:
array2 = np.array([2,4,5])

In [83]:
array2

array([2, 4, 5])

In [84]:
array3 = np.arange(6).reshape(3,2)

In [85]:
array3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [89]:
array4 = np.array([[[1,2,3,5],[3,4,6,5],[7,8,2,5]],[[7,3,4,5],[5,6,7,5],[1,2,4,5]]])

In [90]:
array4

array([[[1, 2, 3, 5],
        [3, 4, 6, 5],
        [7, 8, 2, 5]],

       [[7, 3, 4, 5],
        [5, 6, 7, 5],
        [1, 2, 4, 5]]])

In [91]:
array4.shape #(axis=0, axis=1, axis=2)

(2, 3, 4)

In [92]:
array4.sum(axis=2) #1+2+3+5=11

array([[11, 18, 22],
       [19, 23, 12]])

### 2.1 np.newaxis

In [97]:
array5 = np.arange(12).reshape(2,6)

In [98]:
array5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [99]:
array5.shape

(2, 6)

In [96]:
array5[:,np.newaxis,:].shape

(2, 1, 6)

## 3 array合併&分割

In [101]:
array6 = np.arange(10).reshape(5,2)
array7 = np.arange(6).reshape(3,2)

In [103]:
array6

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [104]:
array7

array([[0, 1],
       [2, 3],
       [4, 5]])

### 3.1 合併:concatenate(), stack(), hstack(), vstack()

In [105]:
#使用 concatenate() 進行陣列的合併時，須留意除了指定的軸之外 (預設為 axis 0)，其他軸的形狀必須完全相同，合併才不會發生錯誤

#### concatenate()

In [106]:
np.concatenate((array6,array7), axis=0, out=None) #axis預設為0, out預設為None

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

#### stack() & &

In [107]:
#stack() 必須要所有陣列的形狀都一樣
#而 hstack() 與 vstack() 則跟上述的規則一樣，除了指定的軸之外，其他軸的形狀必須完全相同才可以合併。

In [110]:
#stack()
c = np.arange(10).reshape(5,2)
np.stack((array6, c), axis=1) ##size一樣 row-row合併

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [111]:
#hstack()
np.hstack((array6, c)) ##橫向合併->row數一樣

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [112]:
#vstack()
np.vstack((array6, array7)) ##直向合併->col數一樣

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

### 3.2 分割:slice(), hsplit(), vsplit()

In [113]:
array8 = np.arange(10).reshape(5,2)

In [114]:
array8

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [115]:
#split()
np.split(array8, 5) ##依照axis0下去分割成多個array

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [168]:
#indices_or_sections 如果給定單一整數的話，那就會按照軸把陣列等分
# 如果給定一個 List 的整數值的話，就會按照區段去分割，例如： indices_or_sections=[2, 3] 會照下列的方式做分割 (一樣是照按照軸把陣列分割)
#ary[:2]
#ary[2:3]
# ary[3:]

In [169]:
array8[:2]

array([[0, 1],
       [2, 3]])

In [170]:
array8[2:3]

array([[4, 5]])

In [171]:
array8[3:]

array([[6, 7],
       [8, 9]])

In [167]:
np.split(array8,[2,3])

[array([[0, 1],
        [2, 3]]), array([[4, 5]]), array([[6, 7],
        [8, 9]])]

In [117]:
array9 = np.arange(30).reshape(5,6)

In [118]:
array9

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [119]:
#hsplit()
np.hsplit(array9,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [122]:
np.hsplit(array9,[2,2,2])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([], shape=(5, 0), dtype=int32),
 array([], shape=(5, 0), dtype=int32),
 array([[ 2,  3,  4,  5],
        [ 8,  9, 10, 11],
        [14, 15, 16, 17],
        [20, 21, 22, 23],
        [26, 27, 28, 29]])]

## 4 迭代

In [128]:
array10 = np.arange(6).reshape(3,2)

In [129]:
array10

array([[0, 1],
       [2, 3],
       [4, 5]])

In [130]:
for i in array10.flat:
    print(i)

0
1
2
3
4
5


In [131]:
for c in array10:
    print(c)

[0 1]
[2 3]
[4 5]


## 5 搜尋&排序

### 5.1 最大值&最小值:amax(),amin(),max(),min()

In [132]:
array11 = np.random.randint(1,20,10)

In [133]:
array11

array([18,  2,  8,  1, 17, 10, 13,  9,  5,  4])

In [134]:
np.amax(array11)

18

In [135]:
np.amin(array11)

1

In [136]:
b = array11.reshape(2,5)

In [137]:
b

array([[18,  2,  8,  1, 17],
       [10, 13,  9,  5,  4]])

In [138]:
np.amax(b, keepdims=True)

array([[18]])

In [139]:
b.max(axis=1)

array([18, 13])

In [140]:
np.amax(b, axis=1)

array([18, 13])

### 5.2 最大值索引&最小值索引: np.argmax()

In [141]:
np.random.seed(0)

In [143]:
array12 = np.random.randint(1, 20, size=(3,4))

In [144]:
array12

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [145]:
np.argmax(array12)

7

### 5.3 找出符合條件的元素: where

In [146]:
np.where(array12 > 10)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 3, 2], dtype=int64))

In [147]:
np.where(array12 > 10, "Y", "X")

array([['Y', 'Y', 'X', 'X'],
       ['X', 'X', 'X', 'Y'],
       ['X', 'X', 'Y', 'X']], dtype='<U1')

### 5.4 nonzero

In [148]:
np.random.seed(2)
array13 = np.random.randint(0, 5, 10)

In [149]:
array13

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [150]:
np.nonzero(array13)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [151]:
array13.nonzero()

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

### 5.5 排序

In [152]:
np.random.seed(3)
array14 = np.random.randint(0, 20, 10)

In [153]:
array14

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [154]:
np.sort(array14) #陣列

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [156]:
array14.argsort() #索引值

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4], dtype=int64)

In [157]:
b = np.random.randint(0, 20, size= (5,4))

In [158]:
np.sort(b, axis=0)

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])

In [159]:
c = np.random.randint(0, 100000000, 100000)

In [160]:
# heapsort
#排序支援多種不同的排序算法，包括 quicksort (預設)、heapsort、mergesort、timesort，在 kind 引數指定即可。依照官網文件指出排序速度是以 quicksort 最快，mergesort / timesort 其次，之後是 heapsort。
np.sort(c, kind="heapsort")

array([     606,     1732,     5838, ..., 99998193, 99998400, 99999830])