# Assignment

In [1]:
import numpy as np 

In [2]:
#1 正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
V1 = 20000
V0 = 20

In [4]:
db = 20*np.log10(V1/V0)

In [5]:
db

60.0

In [3]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?

In [8]:
multiplier1 = 10 ** (30/20)

In [9]:
multiplier1

31.622776601683793

In [10]:
multiplier2 = 10 ** (50/20)

In [11]:
multiplier2

316.22776601683796

In [12]:
multiplier2/multiplier1

10.000000000000002

# Practice

## 1. 四則運算

In [13]:
np.add(1.0, 3.0)

4.0

In [14]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 2, 2, 2, 2])

In [15]:
a + b

array([3, 4, 5, 6, 7])

In [16]:
np.add(a,b)

array([3, 4, 5, 6, 7])

In [17]:
a*b

array([ 2,  4,  6,  8, 10])

In [18]:
a%b

array([1, 0, 1, 0, 1], dtype=int32)

In [19]:
c = np.arange(10)

In [20]:
d = 3

In [21]:
c*d

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [22]:
e = np.random.randint(1, 10, 20).reshape(2, 10)

In [23]:
c + e

array([[ 5,  8,  6,  5, 12,  8, 12, 14, 17, 12],
       [ 8,  5,  9,  5, 10,  9, 14, 12, 17, 16]])

## 2. sum()

In [24]:
a = np.arange(10).reshape(2,5)

In [25]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
a.sum()

45

## 3. 次方: np.power()

In [27]:
np.power(a,b)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

In [28]:
e ** c

array([[       1,        7,       16,        8,     4096,      243,
           46656,   823543, 43046721,    19683],
       [       1,        4,       49,        8,     1296,     1024,
          262144,    78125, 43046721, 40353607]], dtype=int32)

In [29]:
e

array([[5, 7, 4, 2, 8, 3, 6, 7, 9, 3],
       [8, 4, 7, 2, 6, 4, 8, 5, 9, 7]])

In [30]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 4. 平方根: np.sqrt()

In [31]:
np.sqrt(4)

2.0

In [32]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

## 5. Euler's number & 指數函式: np.exp()

In [34]:
np.e

2.718281828459045

In [35]:
np.exp(1)

2.718281828459045

In [36]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

## 6. 對數函式

In [37]:
np.log10(np.array([1, 10, 100, 1000, 10000]))

array([0., 1., 2., 3., 4.])

In [38]:
np.log(9)/np.log(3)

2.0

In [39]:
import warnings
warnings.filterwarnings("ignore")

In [40]:
np.log([-1, 1, 2])

array([       nan, 0.        , 0.69314718])

## 7. 去近似值

In [41]:
f = np.array([1.65, 1.55, -3.57, 2.0])

In [42]:
f

array([ 1.65,  1.55, -3.57,  2.  ])

In [43]:
np.round(f, decimals=1) #小數第一位

array([ 1.6,  1.6, -3.6,  2. ])

In [44]:
# Round至最近的整數
np.rint(f)

array([ 2.,  2., -4.,  2.])

In [45]:
# 無條件捨去小數點
np.trunc(f)

array([ 1.,  1., -3.,  2.])

In [46]:
# 向下取整數
np.floor(f)

array([ 1.,  1., -4.,  2.])

In [47]:
# 向上取整數
np.ceil(f)

array([ 2.,  2., -3.,  2.])

In [48]:
# 向0的方向取整數
np.fix(f)

array([ 1.,  1., -3.,  2.])

## 8. 去絕對值: np.abs(), np.absolute(), np.fabs()

In [49]:
#np.abs() 是 np.absolute() 的簡寫，兩者完全相同
#np.fabs() 的差異在於無法處理複數 (Complex)。

In [50]:
f

array([ 1.65,  1.55, -3.57,  2.  ])

In [51]:
np.abs(f)

array([1.65, 1.55, 3.57, 2.  ])

In [52]:
# 如果傳入複數至 fabs() 的話則會產生錯誤
np.fabs(1+2j)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''