# Assignment

In [1]:
import numpy as np

## 1.有多少學生英文成績比數學成績高?

In [2]:
english_score = np.array([55,89,76,65,48,70])

In [3]:
math_score = np.array([60,85,60,68,55,60])

In [4]:
chinese_score = np.array([65,90,82,72,66,77])

In [5]:
np.greater(english_score, math_score)

array([False,  True,  True, False, False,  True])

## 2.是否全班同學最高分都是國文?


In [12]:
array = np.greater(chinese_score, [english_score, math_score])

In [13]:
array.any()

True

# Practice

## 1 陣列

### 1.1 isnan()

In [14]:
np.isnan(np.array([1.0, np.nan, 3.0]))

array([False,  True, False])

### 1.2 isfinite()

In [15]:
np.isfinite(1.0)

True

In [16]:
np.isfinite(np.nan)

False

### 1.3 isinf(), isposinf(), isneginf()

In [17]:
np.isinf([np.inf, -np.inf, 1.0, np.nan, np.PINF])

array([ True,  True, False, False,  True])

In [18]:
np.isposinf(np.PINF)

True

In [19]:
np.isneginf(np.NINF), np.isneginf(np.nan)

(True, False)

### 1.4 isnat(): Not a Time

In [20]:
np.isnat(np.array(["NaT", "2020-06-26"], dtype="datetime64[ns]"))

array([ True, False])

## 2 陣列型別偵測

### 2.1 isscalar()

In [21]:
a = np.array([1, 2, 3])

In [22]:
np.isscalar(a[2])

True

In [23]:
np.isscalar(a)  ##陣列不是純量

False

In [24]:
np.isscalar(np.pi)

True

In [25]:
np.isscalar(np.array(3.0))

False

In [26]:
np.array(3.0)

array(3.)

### 2.2 isreal(), iscomplex(), isrealobj(), is compleaxobj()

In [27]:
b = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

In [28]:
np.isreal(b)

array([False,  True,  True,  True,  True, False])

In [29]:
np.iscomplex(b)

array([ True, False, False, False, False,  True])

In [30]:
np.iscomplexobj(b)

True

In [31]:
np.isrealobj(b)

False

In [32]:
np.isrealobj(np.array([1, 2.0, 3.1]))

True

## 3 比較

### 3.1 比較2個陣列是否相同: np.array_equal(), np.array_equiv()

In [35]:
np.array_equal((np.array([1, 2, 3])), np.array([1, 2, 3]))

True

In [37]:
np.array_equal((np.array([1, 2, 3])), np.array([1, 2, 5]))

False

In [38]:
np.array_equiv(np.array([1, 2, 3]), np.array([1, 2, 3]))

True

In [39]:
np.array_equiv(np.array([1, 2, 3]), np.array([[1, 2, 3], [1, 2, 3]]))

True

In [40]:
np.array_equiv(np.array([1, 1, 1]), np.array([1])) #元素值均相同，回傳 True

True

### 3.2 等於/不等於, 大於/大於或等於

In [41]:
np.equal(np.array([1, 2, 3]), np.array([1, 2, 3]))

array([ True,  True,  True])

In [43]:
np.equal(np.array([1, 1, 1]), np.ones(1))

array([ True,  True,  True])

In [45]:
np.not_equal([1, 2], [[1, 3],[1, 4]])

array([[False,  True],
       [False,  True]])

# 4. 邏輯操作

In [46]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [47]:
np.logical_and(x, y)

array([ True, False, False, False])

In [49]:
np.logical_or(x, y)

array([ True,  True,  True, False])

In [50]:
np.logical_not(x)

array([False, False,  True,  True])

In [51]:
np.logical_xor(x, y)

array([False,  True,  True, False])

In [52]:
a = np.arange(5)

In [61]:
a

array([0, 1, 2, 3, 4])

In [54]:
np.logical_and(a > 1, a < 4)

array([False, False,  True,  True, False])

# 5 np.all(), np.any()

In [55]:
np.all([-1, np.nan, 5])   #非0

True

In [57]:
np.all([-1, 4, 0])

False

In [59]:
np.any([[True, False], [True, True]])

True

In [60]:
np.any([[True, False], [False, False]], axis=0)

array([ True, False])