# Assignment

In [1]:
import numpy as np

In [2]:
array1 = np.array(range(30))
array2 = np.array([2,3,5])

#1 將下兩列array存成npz檔
**多陣列存一起需要存成npz，讀取須注意npz中有多個陣列**

In [107]:
with open('assignment.npz', 'wb') as f:
    np.savez(f, array1=array1, array2=array2)

In [109]:
npzfile = np.load('assignment.npz')

In [110]:
npzfile.files

['array1', 'array2']

In [111]:
npzfile["array1"]

Exception ignored in: <function ZipFile.__del__ at 0x000001AE96F0C1E0>
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\zipfile.py", line 1789, in __del__
    self.close()
  File "C:\Users\admin\Anaconda3\lib\zipfile.py", line 1806, in close
    self.fp.seek(self.start_dir)
ValueError: I/O operation on closed file.


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

# Practice

## 1. numpy.save(), numpy.savez(), numpy.load()
+ .npy 與 .npz 格式是NumPy的檔案格式，透過 save()、savez()、load() 函式進行儲存與讀取

In [3]:
with open('one_array.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))

In [4]:
np.load('one_array.npy')

array([1, 2])

In [5]:
with open('test.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))
    np.save(f, np.array([1, 3]))
    np.save(f, np.array([1, 4]))
    np.save(f, np.array([1, 3]))

In [6]:
#每次只載入一個陣列
with open('test.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    d = np.load(f)

print(a, b, c, d)

[1 2] [1 3] [1 4] [1 3]


In [72]:
#使用 numpy.savez() 時，可以儲存多個陣列。
x = np.arange(10)
y = np.array([1, 2, 3])
z = np.random.rand(10)

with open('multi_array.npz', 'wb') as f:
    np.savez(f, array1=x, array2=y, array3=z)

In [71]:
npzfile = np.load('multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [9]:
npzfile.files

['array1', 'array2', 'array3']

In [10]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.81614523 0.35486497 0.45103574 0.84435794 0.65329705 0.12340665
 0.32246994 0.62394926 0.53987829 0.25615681]


## 2. savetxt(), loadtxt()

### 2.1 numpy.savetxt()
+ numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='n', header='', footer='', comments='# ', encoding=None)

In [11]:
x = y = z = np.arange(0.0,5.0,1.0)
x

array([0., 1., 2., 3., 4.])

In [12]:
y = np.arange(10).reshape(2, 5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
np.savetxt("test.out", [x], delimiter=",")

#### 使用 %load <filename> magic command 來查看檔案內容。

In [ ]:
# %load test.out
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


In [17]:
# 如果副檔名為 .gz 的話，存檔時會存為壓縮的 gzip 檔案。
np.savetxt('test.gz', [x], delimiter=',') 

In [19]:
%load test.gz #會失敗

SyntaxError: invalid or missing encoding declaration for 'test.gz' (<string>)

In [20]:
np.savetxt('test.csv', y, delimiter=',')

In [25]:
# %load test.csv
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00


(5.0, 6.0, 7.0, 8.0, 9.0)

In [22]:
np.savetxt('test.out', x, fmt='%1.4e', delimiter=',', header='this is,\nheader', footer='this is footer')

In [24]:
# %load test.out
# this is,
# header
0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00
# this is footer


4.0

### 2.2 numpy.loadtxt()

In [26]:
# 在 dtype 引數中 f4 代表的是浮點數 4 bytes，也就是 float32
np.loadtxt('test.out', delimiter=',', dtype='f4')

array([0., 1., 2., 3., 4.], dtype=float32)

## 3. genfromtxt()

### 3.1 將文字檔內容讀取並正確分隔Column

In [27]:
np.genfromtxt("test.csv", delimiter=",")

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

#### 跟 loadtxt() 相同，如果檔案是 gz 或是 bz2 壓縮檔的話，可以直接讀取不需要先解壓縮。

In [28]:
np.genfromtxt("test.gz", delimiter=",") 

array([0., 1., 2., 3., 4.])

In [29]:
np.genfromtxt(["1", "2", "abc", "4", "5"])

array([ 1.,  2., nan,  4.,  5.])

StringIO建立的是一個file-like object，擁有File Object的所有方法。StringIO還有兩個特殊的方法，就是getvalue()方法和close()方法。

getvalue()方法用於獲取StringIO中寫入的內容

close()方法關閉StringIO，釋放記憶體。

In [34]:
from io import StringIO

data = "  1  2  3\n  4  5 67\n890123  4"

# 當 delimiter 給定的是一個整數、或是整數的序列時，可以用來將固定寬度的字串讀入，
# 在下面的範例中，固定寬度包含了空格。
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [35]:
data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [38]:
data = u"1, 2 , 4\n 4, 5, 6"
# autostrip 引數如果設為 True，在讀取時會自動將元素值的空格去除。
np.genfromtxt(StringIO(data), delimiter=",", autostrip=True)

array([[1., 2., 4.],
       [4., 5., 6.]])

In [39]:
#在檔案內容中包含了以 # 啟始的 header / footer。
# header 有 2 行而 footer 有 1 行，
# 設定要略過的行數就可以正確讀入欲讀取的陣列元素。
np.genfromtxt("test.out", comments="#")

array([0., 1., 2., 3., 4.])

In [40]:
np.genfromtxt("test.out", comments=None, skip_footer=1, skip_header=2)

array([0., 1., 2., 3., 4.])

### 3.2 選擇要讀取的column

In [44]:
# names.txt 中的第一行是預期的Column名稱。
# %load names.txt
a,b,c
1,2,3
4,5,6
7,8,9

(7, 8, 9)

In [45]:
np.genfromtxt("names.txt", delimiter=",", names=True)

array([(1., 2., 3.), (4., 5., 6.), (7., 8., 9.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [46]:
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, names="a, b, c")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('a', '<f8'), ('b', '<f8'), ('c', '<f8')])

In [47]:
a = u"1,2,3,4,5\n6,7,8,9,10"
# 透過 usecols 引數可以選擇要讀入的Column，下面的例子是指定要讀入的Column名稱。
np.genfromtxt(StringIO(a), delimiter=",", names="a, b, c", usecols=("a", "c"))

array([(1., 3.), (6., 8.)], dtype=[('a', '<f8'), ('c', '<f8')])

In [48]:
a = u"1 2 3 4 5\n6 7 8 9 10"
np.genfromtxt(StringIO(a), usecols=(1, -1))

array([[ 2.,  5.],
       [ 7., 10.]])

In [49]:
a = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(a, dtype=(int, float, int))

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '<i4')])

In [50]:
a = StringIO("1 2 3\n 4 5 6")
# 若要指定命名規則，可以使用 defaultfmt 引數。
np.genfromtxt(a, dtype=(int, float, int), defaultfmt="var_%i")

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('var_0', '<i4'), ('var_1', '<f8'), ('var_2', '<i4')])

### 3.3 缺值處理

In [51]:
a = u", 2, 3\n4, ,"
np.genfromtxt(StringIO(a), delimiter=",", filling_values=np.nan)

array([[nan,  2.,  3.],
       [ 4., nan, nan]])

In [52]:
a = u"N/A, 2, 3, ???"
np.genfromtxt(StringIO(a), delimiter=",", 
              missing_values=["N/A", "N/A", "N/A", "???"], 
              filling_values=[0, 0, 0, -999])

array([   0.,    2.,    3., -999.])

### 3.4 資料轉換

In [54]:
np.genfromtxt("transform.txt", delimiter=',', dtype="i8, i8, U3, U3")

array([(1, 2, 'Yes', '87%'), (3, 4, 'No', '3%'), (5, 6, 'Yes', '55%')],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<U3'), ('f3', '<U3')])

舉例來說，如果我們想將資料中的Yes/No與百分比進行轉換，使用自訂函式來進行。

**補充**
+ 1.字串前加u: 後面字串以 Unicode 格式 進行編碼，一般用在中文字串前面，防止因為原始碼儲存格式問題，導致再次使用時出現亂碼。 
+ 2.字串前加r: 聲明後面的字串是普通字串，相對的，特殊字串中含有：轉義字元 \n \t 什麼什麼的
+ 3.字串前加b: python3.x裡預設的str是(py2.x裡的)unicode, bytes是(py2.x)的str, b”“字首代表的就是bytes。python2.x裡, b字首沒什麼具體意義， 只是為了相容python3.x的這種寫法

In [55]:
def trans(s):
    if s == b'Yes':
        return 1
    else:
        return 0

In [60]:
def conversion(x):
    return float(x.strip(b"%"))/100

In [61]:
np.genfromtxt("transform.txt", delimiter=',', converters={2:trans, 3:conversion})

array([(1., 2., 1, 0.87), (3., 4., 0, 0.03), (5., 6., 1, 0.55)],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<i4'), ('f3', '<f8')])