In [24]:
array1 = np.array([[10, 8], [3, 5]])

# 1運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣? 是

In [26]:
inv = np.linalg.inv(array1)

In [27]:
inv

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [29]:
result = inv@array1

In [30]:
result

array([[1., 0.],
       [0., 1.]])

# 2 運用上列array計算特徵值、特徵向量?

In [31]:
np.linalg.eig(array1)

(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

# 3 運用上列array計算SVD?

In [32]:
np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))