In [1]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [2]:
import numpy as np

# 將上列 list 依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入 array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

In [60]:
dt4 = np.dtype({"names":("name", "sex", "weight", "rank", "myopia"), "formats":("U17","U4",float,int,bool)})

In [62]:
students = np.zeros(8,dtype=dt4)

In [63]:
students["name"] = name_list
students["sex"] = sex_list
students["weight"] = weight_list
students["rank"] = rank_list
students["myopia"] = myopia_list

In [64]:
print(students)

[('小明', 'boy', 67.5, 8,  True) ('小華', 'boy', 75.3, 1,  True)
 ('小菁', 'girl', 50.1, 5, False) ('小美', 'girl', 45.5, 4, False)
 ('小張', 'boy', 80.8, 7,  True) ('John', 'boy', 90.4, 6,  True)
 ('Mark', 'boy', 78.4, 2, False) ('Tom', 'boy', 70.7, 3, False)]


# 呈上題，將 array 中體重(weight)數據集取出算出全部平均體重

In [65]:
np.average(students["weight"])

69.8375

# 呈上題，進一步算出男生(sex 欄位是 boy)平均體重、女生(sex 欄位是 girl)平均體重

In [108]:
np.piecewise( students["weight"], [students["sex"] == "boy"],[lambda x: x])

array([67.5, 75.3,  0. ,  0. , 80.8, 90.4, 78.4, 70.7])

In [109]:
np.nonzero(np.piecewise( students["weight"], [students["sex"] == "boy"],[lambda x: x]))

(array([0, 1, 4, 5, 6, 7], dtype=int64),)

In [110]:
students["weight"][np.nonzero(np.piecewise( students["weight"], [students["sex"] == "boy"],[lambda x: x]))]

array([67.5, 75.3, 80.8, 90.4, 78.4, 70.7])

In [104]:
boy_avg = students["weight"][np.nonzero(np.piecewise( students["weight"], [students["sex"] == "boy"],[lambda x: x]))].mean()

In [111]:
boy_avg ###############

77.18333333333332

In [106]:
girl_avg = students["weight"][np.nonzero(np.piecewise( students["weight"], [students["sex"] == "girl"],[lambda x: x]))].mean()

In [107]:
girl_avg #####################

47.8

# Practice

In [ ]:
# %load structured.txt
Jay,1,2,Yes,87%
James,3,4,No,3%
Joe,5,6,Yes,55%

In [13]:
dt = np.dtype('i8, i8, U5, U3') 
#字母後的數字代表其長度，例如 f8 代表 float64 (8 bytes)，U5代表長度5以下的unicode字串。

In [14]:
dt2 = np.dtype("U5, i8, i8, U3, U5")

In [10]:
a = np.genfromtxt("structured.txt", delimiter=",", dtype=dt)

In [11]:
a

array([(-1, 1, '2', 'Yes'), (-1, 3, '4', 'No'), (-1, 5, '6', 'Yes')],
      dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<U5'), ('f3', '<U3')])

In [15]:
b = np.genfromtxt("structured.txt", delimiter=",", dtype=dt2)

In [16]:
b

array([('Jay', 1, 2, 'Yes', '87%'), ('James', 3, 4, 'No', '3%'),
       ('Joe', 5, 6, 'Yes', '55%')],
      dtype=[('f0', '<U5'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<U3'), ('f4', '<U5')])

# 建立結構化陣列

In [17]:
dt3 = np.dtype({'names':('Name', 'num1', 'num2', 'True'), 'formats':((np.str_, 5), np.int32, int, 'U3')})

In [18]:
c = np.genfromtxt("structured.txt", delimiter=',', dtype=dt3)

In [19]:
c

array([('Jay', 1, 2, 'Yes'), ('James', 3, 4, 'No'), ('Joe', 5, 6, 'Yes')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

# 建立結構化陣列2

In [20]:
d = np.zeros(3, dtype=dt3)

In [21]:
d

array([('', 0, 0, ''), ('', 0, 0, ''), ('', 0, 0, '')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

In [22]:
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

In [23]:
d['Name'] = name
d['num1'] = num_1
d['num2'] = num_2
d['True'] = check

In [24]:
d

array([('Chloe', 11, 14, 'Y'), ('Charl', 12, 15, 'Y'),
       ('Clara', 13, 16, 'N')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i4'), ('True', '<U3')])

In [25]:
print(d)

[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]
